### ISSUE TITLE
Sometimes segmentation fault when using selectrum-mode

### ISSUE THREAD

**Issue by declantsien** [masm11/emacs#100]
Steps to reproduce.
- Enable selectrum-mode(or ivy-mode)
- async-shell-command (M-&)
- Hit Tab

```
  Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
Factive_minibuffer_window () at minibuf.c:222
222	  innermost_MB = nth_minibuffer (minibuf_level);
```

**Comment by masm11** [comment]
It does not reproduce...

**Comment by declantsien** [comment]
Yeah, true. Just started a instance with `emacs -Q` then loaded `selectrum.el`
file and enabled `selectrum-mode`. Worked as expected.

Will reopen this issue when I found a simple way to reproduce this.
