### ISSUE TITLE
Super key problem

### ISSUE THREAD

**Issue by abcdw** [masm11/emacs#103]
In recent versions of pgtk branch when I press Win+e, Emacs says `H-s-e is undefiend`, but it should be `s-e is undefiened`, Emacs from master branch works correctly.

**Comment by masm11** [comment]
I fixed that.  Please try latest feature/pgtk on savannah.

**Comment by abcdw** [comment]
Thank you.

Now it works as expected, the same way as in vanilla emacs.

And thank you very much for all your work!)
