### ISSUE TITLE
org-roam-mode+marginalia-mode hangs `C-h v`

### ISSUE THREAD

**Issue by abcdw** [masm11/emacs#104]
Hi again!)

Found a bug, which hangs emacs. I was able to reproduce on latest commits of pgtk branch. Master branch, 27.2, earlier commits of pgtk branch (i tried something from feb) are not affected.

Way to reproduce: 
1. install org-roam and marginalia.
2. `emacs -q`
3. `M-x marginalia-mode`, `M-x org-roam-mode`, `C-h v TAB`
4. Profit)

**Comment by abcdw** [comment]
It seems the issue was resolved.  Thanks a lot!)

**Comment by masm11** [comment]
??  I didn't do anything...

**Comment by abcdw** [comment]
Yuuki Harano ***@***.***> writes:

> ??  I didn't do anything...

Probably some changes in the upstream branch fixed it, after I built
emacs from latest commit on pgtk branch everything works correctly.

Anyway, thank you for working on the feature/pgtk!)
