### ISSUE TITLE
Empty new frame after disabled menu/scroll/tool bar

### ISSUE THREAD

**Issue by declantsien** [masm11/emacs#105]
Commands below should be enough to reproduce the issue

`emacs -Q --eval "(scroll-bar-mode -1)" --eval "(menu-bar-mode -1)" --eval "(tool-bar-mode -1)" --eval "(make-frame-command)"`

----
`system-configuration-options`

`--with-pgtk --with-xft --with-wide-int --with-modules --with-cairo --with-harfbuzz 'CFLAGS=-march=x86-64 -mtune=generic -O2 -pipe -fno-plt' CPPFLAGS=-D_FORTIFY_SOURCE=2 LDFLAGS=-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now --with-native-compilation`

Git commit hash
https://github.com/emacs-mirror/emacs/tree/4b91168c657e3476b8a0a3f539ee6bcb1b71e3d5

---
https://i.imgur.com/PWJISwG.png

**Comment by masm11** [comment]
Thank you for the speedy report.
The issue is by the last two commits.  I reverted them for now, and the issue should be gone.

**Comment by declantsien** [comment]
Cool. Ok to close this issue then.

**Comment by masm11** [comment]
I re-applied the commits, debugged, and now this issue should be fixed.
Could you confirm?

**Comment by declantsien** [comment]
Pulled the changes, compiled. And it works fine now. 
I confirm that the empty frame issue is gone. Nice work. :+1:

**Comment by masm11** [comment]
Thanks.
