### ISSUE TITLE
compilation error due to empty last case in switch 

### ISSUE THREAD

**Issue by collares** [masm11/emacs#112]
The removal of the PGTK_TRACE call at https://github.com/emacs-mirror/emacs/blob/901938109f7b5574e97e787bee10441086680de8/src/pgtkterm.c#L4450 (in https://github.com/emacs-mirror/emacs/commit/901938109f7b5574e97e787bee10441086680de8) caused the following error:

```
pgtkterm.c: In function 'set_fullscreen_state':
pgtkterm.c:4278:10: error: label at end of compound statement
 4278 |     case FULLSCREEN_HEIGHT:
      |          ^~~~~~~~~~~~~~~~~
make[1]: *** [Makefile:409: pgtkterm.o] Error 1
make[1]: Leaving directory '/build/source/src'
make: *** [Makefile:459: src] Error 2
```

Adding a `break` should be enough to fix it.

**Comment by masm11** [comment]
Thanks.
The issue seems to have been fixed.
