### ISSUE TITLE
Non-english layout

### ISSUE THREAD

**Issue by ghost** [masm11/emacs#30]
Without `(pgtk-use-im-context t)` I couldn't input russian characters, only codes like this  ![image](https://user-images.githubusercontent.com/9449246/87835554-ffb87500-c87c-11ea-8371-32cd8decd356.png)

But even with GtkIMContext, as you wrote in the readme, keys with modifiers still handled by emacs, and that way tools like https://github.com/a13/reverse-im.el doesn't work properly, so is there some way to fix it?

**Comment by leezu** [comment]
There's a similar issue with umlauts (äöü)

**Comment by masm11** [comment]
Thank you, non-English users.
I don't know how you input non-English text.

How to input russian text or umlauts?  What emacs lisps or other programs do you use?

**Comment by ghost** [comment]
> How to input russian text

Russian keyboard looks like this
![image](https://i.pinimg.com/originals/6d/57/6a/6d576ae02618b777116dad46b7842ff7.png)

it's as if japanese only had hiragana, and then there would be no reason to use ibus, or other IM, I guess. You configure layout, through xorg settings, setxkbmap, or compositor - dependent options on wayland. Then just switch between the two layouts with configured shortcut.

> What emacs lisps or other programs do you use?

I use [doom-emacs](https://github.com/hlissner/doom-emacs/) in evil mode, so there's plenty of emacs packages. As for the other programs - I write this in firefox, for example. Maybe there's something specific that you want to know?

**Comment by masm11** [comment]
> it's as if japanese only had hiragana, and then there would be no reason to use ibus, or other IM, I guess.

Since Japanese people need to input Kanji, we need to use ibus or such programs
to convert Hiragana to Kanji.  Also such programs can convert alphabet to
Hiragana, so many Japanese people don't input Hiragana directly.
However some people switch keyboard layouts, input Hiragana directly, and
convert it to Kanji by using ibus or something.

I have forgot direct input of non-English characters.


> > What emacs lisps or other programs do you use?

> I use doom-emacs in evil mode, so there's plenty of emacs packages. As for the other programs - I write this in firefox, for example. Maybe there's something specific that you want to know?

I was going to ask what emacs lisps or other programs you are using *to input non-English text*.
The answer is "nothing"?

**Comment by ghost** [comment]
> The answer is "nothing"?

Yeah, that's right. And reverse-im.el is just a convenience tool.

**Comment by masm11** [comment]
Maybe reproduced by directly inputting Katakana.

![screenshot-20200720-205947](https://user-images.githubusercontent.com/7226237/87935432-14d71300-cacc-11ea-8716-0917b27ca3be.png)

**Comment by masm11** [comment]
@Svadkos 
Fixed.  I can input Katakana directly.

![screenshot-20200720-220053](https://user-images.githubusercontent.com/7226237/87942073-06dabf80-cad7-11ea-8b30-25f4c4fe901f.png)

Could you try #31?  You should be able to input russian characters and maybe use reverse-im without GtkIMContext.

**Comment by ghost** [comment]
Applied it on top of https://github.com/masm11/emacs/pull/23 and it works with and without GtkIMContext. Thank you.

**Comment by masm11** [comment]
Hi, @fejfighter,
could you pull in #31?

**Comment by fejfighter** [comment]
@Svadkos should be included, with latest changes from master

@masm11 Thanks, Done!

**Comment by ghost** [comment]
Thanks
