### ISSUE TITLE
configure: error: xwidgets requested but gtk3 not used

### ISSUE THREAD

**Issue by elandx** [masm11/emacs#32]
Hi. Sorry for noob question. 
Then trying to compile i got the error: 
`configure: error: xwidgets requested but gtk3 not used`. 
I am on Arch Linux, seems all listed dependencies installed. 
Thanks in advance.

**Comment by masm11** [comment]
Thank you for your report.

Did you use PKGBUILD?  Then, I updated the file now.

Please try once again.

**Comment by elandx** [comment]
Thank you very much for your super quick and helpful reply!
Yes, of course i used PKGBUILD.
Now I'll try with a new one.
Thanks again

**Comment by elandx** [comment]
Thanks a lot, now everything is OK.
