### ISSUE TITLE
pdf-tools issue

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#34]
First of all, I can't thank you enough for this fork, Emacs not being a native wayland app causes some 'issues'.

Whenenevr I run `pdf-view-auto-slice-minor-mode` on `pdf-tools` I get  a glitched pdf preview
 
![image](https://user-images.githubusercontent.com/11528996/89334776-97dc9980-d686-11ea-8ed2-958b2ea15053.png)

Not only the right third of the image is ill scaled but the lower third is also weird (the text does not repeat Lemma 0.1 thrice).

This started happening when I switched from vanilla emacs 27.0.91 to the `pgtk-nativecomp` branch of https://github.com/fejfighter/emacs, so it is still possible that this is a `native-comp` bug.

**Comment by A6GibKm** [comment]
I'll add another preview

![image](https://user-images.githubusercontent.com/11528996/89335295-5b5d6d80-d687-11ea-9ae5-f3992a674e9d.png)

**Comment by masm11** [comment]
![repro](https://user-images.githubusercontent.com/7226237/89416412-2ecd5280-d768-11ea-89e7-8ebd28c10e10.png)

I can reproduce something similar.  I'll debug that.

**Comment by A6GibKm** [comment]
A similar issue arises when showing images in elfeed-mode, 

![image](https://user-images.githubusercontent.com/11528996/89550112-bcf11980-d7f8-11ea-889b-b866a4781759.png)

Here, instead of showing the image I see the contents of the previous buffer `elfeed-search`

**Comment by masm11** [comment]
I fixed it in #37.  Please try it.
If really fixed, I'll merge it into pgtk.

![fixed](https://user-images.githubusercontent.com/7226237/89773554-1cc02b00-db3f-11ea-9604-844b8b5ba3e2.png)

**Comment by A6GibKm** [comment]
I tested it and it fixes both the issue on pdf-tools and elfeed on first inspection.

**Comment by masm11** [comment]
thanks.
