### ISSUE TITLE
Mouse does not reappear after writing

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#35]
Sometimes while using Emacs the mouse will disappear, clicking on the screen solves the issue.

This is using the `pgtk-nativecomp` branch but I am sure the issue was there in the `pgtk` build too.

**Comment by masm11** [comment]
Can you tell me about your environment?

**Comment by A6GibKm** [comment]
Fedora Silverblue 32
Gnome 3.36
Kernel 5.7.10
Happens both on my thinkpad and my amd desktop.

There is also the fact that I run emacs from insde toolbox (podman wrapper). This issue happens relatively often so it might be due to my environment.

I am sorry for the lack of details, but I have not been able to determine how to reproduce it yet.

**Comment by A6GibKm** [comment]
I did some testing and it was pretty simple to reproduce actually, just type anything or add a newline with `<return>` on a buffer, e.g. `*scratch*`.

This was tested both on sway 1.4 and gnome 3.36, it was also tested without my personal configuration and with doom emacs.

Finally, it was also tested with the emacs flatpak at https://github.com/fejfighter/pgtk-emacs-flatpak, which discards toolbox as the source of the issue.

**Comment by A6GibKm** [comment]
Actually, it also happens with vanilla Emacs from fedora repos. The bug just appeared the literally same day I switched to the `pgtk` build.

Edit, it is not the same bug, the difference being that the mouse re appears after moving the cursor in vanilla emacs 26.3.

**Comment by A6GibKm** [comment]
Update, the issue is related to `make-pointer-invisible`. The mouse is supposed to disappear in Emacs while typing, but for some reason it does not re-appear in the `pgtk` branch after moving the mouse. As a temporal fix I used

```lisp
(setq make-pointer-invisible nil)
```

**Comment by masm11** [comment]
thanks.  reproduced.

**Comment by masm11** [comment]
It should be fixed in pgtk branch now.

Could you test?

**Comment by A6GibKm** [comment]
Tested, that fixed it. Thanks.
