### ISSUE TITLE
Childframes offset incorrectly

### ISSUE THREAD

**Issue by rushsteve1** [masm11/emacs#46]
Childframes, like those created by [`company-box`](https://github.com/sebastiencs/company-box) are offset incorrectly, so far to the left that they are off the Emacs window.
![image](https://user-images.githubusercontent.com/5970439/90969746-3b70db00-e4ca-11ea-9897-f0c337fba57d.png)

The childframes appear to be offset based on the global amount, instead of relative to the Emacs window.

OpenSUSE Tumbleweed
X11, KDE 5.19.4
`GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21, cairo version 1.16.0)`
Doom Emacs commit `a8b7c00426edd76ba7f5269403fcdf8eb2c56a30`
Company-Box commit `20384f0e382c063173b9d863344b1b23bc1e4954`

**Comment by fejfighter** [comment]
@rushsteve1 is this "pure" X11 or xwayland on wayland?  I have had mixed results with the latter but previous testing was fine for X only

**Comment by flatwhatson** [comment]
I am seeing the same with Plasma on xorg (not xwayland).

ArchLinux
plasma-desktop 5.19.4-1

**Comment by A6GibKm** [comment]
Can't reproduce in GNOME.

**Edit:** Can't reproduce in sway either.

**Comment by fejfighter** [comment]
> Can't reproduce in GNOME.
> 
> **Edit:** Can't reproduce in sway either.

Sounds like it's an X v Wayland issue, I think GTK will return different info based on the backend

**Comment by fejfighter** [comment]
Ok Can confirm on X.org Gnome, I'll have a dig

**Comment by fejfighter** [comment]
@rushsteve1 @flatwhatson 

try #47 or latest #23

**Comment by flatwhatson** [comment]
That's working properly for me, thanks! :heart:

**Comment by masm11** [comment]
fixed by #51.
