### ISSUE TITLE
Childframe remains after losing focus

### ISSUE THREAD

**Issue by flatwhatson** [masm11/emacs#48]
Childframes remain "on top" after Emacs loses focus, or changing virtual desktop.

Before changing focus:
![childframe-overlap-1](https://user-images.githubusercontent.com/24718616/91434798-b2321d80-e8a8-11ea-976c-4ed68c9c879c.png)

After changing focus:
![childframe-overlap-2](https://user-images.githubusercontent.com/24718616/91434907-d7bf2700-e8a8-11ea-801c-0df6530be363.png)

After changing desktop:
![childframe-overlap-3](https://user-images.githubusercontent.com/24718616/91434944-e574ac80-e8a8-11ea-92e1-a2c04cdccdc7.png)

I'm running the X11 backend on Plasma.

**Comment by fejfighter** [comment]
I think I will need to investigate how gnome builder does it's completion popups, I know emacs is weird, but I'm already setting every association in gtk_window_*

this is confirmed as is #49

**Comment by fejfighter** [comment]
in spite of what I said on #49 I think this still applies for wayland, though it;s not as dramatic, "clicking out" of a completion with company-posframe does not drop the child frame and that should.

**Comment by masm11** [comment]
fixed by #51.
