### ISSUE TITLE
Cursor not showing when starting or when refocusing Emacs

### ISSUE THREAD

**Issue by jacksonludwig** [masm11/emacs#52]
When opening emacs, the mouse cursor is invisible. I have to manually unfocus and refocus the window to get it to appear. I must do this using my keyboard however -- clicking on emacs with my mouse does not make the cursor reappear.

This issue also sometimes occurs when I click another window with my mouse while emacs is open. I am once again forced to refocus emacs using my keyboard as clicking keeps the cursor hidden.

---

I built Emacs through an aur package https://github.com/flatwhatson/emacs#branch=pgtk-nativecomp which just yesterday updated to this repo's latest commit.

I am using Arch Linux with LightDM and i3. 

This does not occur on the non-pgtk branches (not on 27.1 nor on native-comp).

I have also seen the same issue on my manjaro i3 PC, and I have had at least one other person who uses Arch and i3 confirm that they have the same problem.

**Comment by masm11** [comment]
I couldn't reproduce it on GNOME(Xorg).  I'll try lightdm + i3 later.

**Comment by masm11** [comment]
I tried lightdm + i3 and built flatwhatson's pgtk-nativecomp, but it did not occur.

**Comment by jacksonludwig** [comment]
Maybe it matters that it's i3 gaps instead of i3? I don't understand what else it could be if it isn't related to i3. Thanks for your efforts.

**Comment by masm11** [comment]
Could you give me your `~/.config/i3/config`?

**Comment by jacksonludwig** [comment]
Sorry, I should have updated this issue but I totally forgot; at some point one of the updates to this fixed the issue where it started unfocused!
