### ISSUE TITLE
possible to rebase on native-comp branch?

### ISSUE THREAD

**Issue by xeijin** [masm11/emacs#55]
I have no clue how difficult this would make development, but the emacs native-comp branch (https://github.com/emacs-mirror/emacs/tree/feature/native-comp) brings some pretty significant performance improvements - any chance we could rebase based on this branch?

**Comment by A6GibKm** [comment]
Check out the `pgtk-nativecomp` branch of https://github.com/fejfighter/emacs. There are builds for guix/nix and [fedora](https://copr.fedorainfracloud.org/coprs/deathwish/emacs-pgtk-nativecomp/packages/) already available using both codebases.
