### ISSUE TITLE
amazing that this is finally happening

### ISSUE THREAD

**Issue by titaniumbones** [masm11/emacs#56]
just wanted to say that I installed the AUR package on Arch linux and I can't believe I finally have a gtk emacs after all these years.  Really, I'm so very grateful.  Thanks.

**Comment by masm11** [comment]
thank you for the message!

**Comment by telent** [comment]
Don't want to add to your open issues list, so here I am commenting on the closed one with a similar message. Fuzzy fonts in Emacs (I use non-integer scaling in Wayland) have been getting me down for a while, this is so much better.  Thanks!
