### ISSUE TITLE
Mouse disapears on xwidgets

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#62]
When opening a webpage using `xwidget-webkit-browse-url`, the mouse disapears when it is above the buffer. It appears once again after it hits the scrollbar, and there are problably other triggers for it to fix itself.

**Screencast**: https://imgur.com/a/9oUcPDi
If the quality is bad, here is the original: [Screencast.zip](https://github.com/masm11/emacs/files/5295432/Screencast.zip)

## Environment

Fedora Silverblue 33
GNOME 3.38
Wayland

## How to reproduce

- Compile emacs with `./configure --with-cairo --with-modules --with-xwidgets --with-pgtk`
- `$ emacs -Q`
- `M-x xwidget-webkit-browse-url` and enter some url
- Move mouse above buffer

**Disclaimer:** Due to some issue with my OS I am unable to run Emacs without pgtk, and therefore to test this in a clean setting.

**Comment by masm11** [comment]
reproduced.
thanks for finding this issue.
it seems to be a mainloop-related issue, and is very difficult.  i'll try to debug.

**Comment by A6GibKm** [comment]
Try to see if this is reproducible in a non-pgtk emacs build. Sadly I can't test that myself and the flatpak version which I can test is not built with xwidgets.

**Comment by masm11** [comment]
It is not reproducible on X-build.

**Comment by masm11** [comment]
> it seems to be a mainloop-related issue,

That was misunderstanding.

Try #65.

**Comment by A6GibKm** [comment]
Fixed by #65.
