### ISSUE TITLE
GTK Error on childframes Pt II

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#64]
Somewhat related to #61. When running certain childframes from company-mode an error

```
(emacs:722892): Gtk-CRITICAL **: 15:05:45.917: gtk_window_set_focus_on_map: assertion 'GTK_IS_WINDOW (window)' failed

(emacs:722892): Gtk-CRITICAL **: 15:05:46.586: gtk_window_set_focus_on_map: assertion 'GTK_IS_WINDOW (window)' failed
```

Appears.

## Environment

Wayland & GNOME 3.38

## How to reproduce

With the following `~/.emacs` config:
```lisp
;;; ~/.emacs -*- lexical-binding: t; -*-

(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/"))
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(use-package company
  :ensure t)

(use-package company-box
  :ensure t)
```
Run `emacs` from a terminal. Then, on a lisp mode buffer activate both modes

- `M-x company-mode`
- `M-x company-box-mode`

And as in a previous issue, invoke company mode by writing `(des`

**Comment by A6GibKm** [comment]
Similar to the previous issue, it seems this is not harmful and the childframes do appear as expected.

![image](https://user-images.githubusercontent.com/11528996/94563139-c9707c00-0255-11eb-931c-ee82df967c83.png)

**Comment by A6GibKm** [comment]
#68 Fixes the issue. Tested and no regressions that I know of were found.

**Comment by masm11** [comment]
Thanks. Merged.
