### ISSUE TITLE
X-Widget: instance with invalid (NULL) class pointer

### ISSUE THREAD

**Issue by A6GibKm** [masm11/emacs#72]
When Running the exact same file as described in #71, Closing the buffer via `kill-buffer` yields en error (aditionally to the error seen in #71)

```
(emacs:151415): GLib-GObject-WARNING **: 12:18:44.591: instance with invalid (NULL) class pointer

(emacs:151415): GLib-GObject-CRITICAL **: 12:18:44.591: g_signal_handlers_disconnect_matched: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
```

**Note:** I will test later if these bugs are reproducible in the master branch of Emacs.

**Comment by fejfighter** [comment]
Confirmed on master

**Comment by A6GibKm** [comment]
Will file a report.

**Comment by A6GibKm** [comment]
Closed as it is a master bug. @masm11 you could re-open if you consider it falls under the scope of the pgtk project.
