### ISSUE TITLE
Bind with super key doesn't work

### ISSUE THREAD

**Issue by abcdw** [masm11/emacs#80]
Hi, @masm11!
Thank you for your great work.

Have an issue with bindings using super key (win key).
`(global-set-key (kbd "s-o") 'other-window)` evaluates properly, but pressing `s-o` just inserts o in the buffer.

**Comment by A6GibKm** [comment]
In my setup (GNOME+Wayland) the `s-o` or `Windows key` + `o` does nothing.

**Comment by abcdw** [comment]
I also tried to use key chord `s-b` (it's not bound in both: emacs and wm). In my current vanilla 27 emacs it says `s-b is undefined`, in masm11's fork with `--with-pgtk` flag it inserts `b` in normal buffer. In greeting buffer it says `b is undefined`.

It's true for both X11 and Wayland.

**Comment by masm11** [comment]
Thank you for the reports.

Please try #81.

**Comment by abcdw** [comment]
#81 fixes the problem. Thank you!

**Comment by A6GibKm** [comment]
Seems there are no regressions.

**Comment by masm11** [comment]
thanks for testing.
