### ISSUE TITLE
Ligatures support

### ISSUE THREAD

**Issue by rainD4X** [masm11/emacs#82]
Ligatures do not render when using emacs pgtk

![emacs pgtk](https://user-images.githubusercontent.com/34621487/100234812-e8288180-2f2b-11eb-99f5-0494f239ea43.png)
For comparison, here it is how it render using emacs vanilla (a bit blurry because of xwayland's scaling).
![emacs vanilla](https://user-images.githubusercontent.com/34621487/100234809-e78feb00-2f2b-11eb-863d-33fbe5910dbb.png)

### How to reproduce
- Set a font with ligature support (e.g. FiraCode or Cascadia Code)
- install [ligature.el](https://github.com/mickeynp/ligature.el) and configure it (the default config provided in the README should be enough)

### My environment
archlinux
gtk3 3.24.23
cairo 1.17.2
harfbuzz 2.7.2
sway 1.5.1

**Comment by masm11** [comment]
I can't enable ligatures on X-build.

0. Install Fira Code font.
1. Build X-emacs.
2. `./src/emacs -Q`
3. evaluate `(set-fontset-font nil nil "Fira Code")`.
4. load `ligature.el` and evaluate it.
5. evaulate commented config snippet.
6. I typed "www" on some buffers.  It is not ligatured.

What's wrong?

**Comment by rainD4X** [comment]
To enable ligatures I do as follows ( Keep steps 0, 1 and 2): 

3. evaluate `(set-face-attribute 'default nil :font "Fira Code")`.
4. load `ligature.el` and evaluate it.
5. evaluate `(ligature-set-ligatures 't '("www"))` `(ligature-mode 1)` 
6. www should be ligatured

**Comment by rainD4X** [comment]
Or alternatively, without needing ligature.el at all :
3. evaluate 
```elisp
(set-face-attribute 'default nil :font "Fira Code")
(let ((ligatures `((?w  . ,(regexp-opt '("www")))
		 (?&  . ,(regexp-opt '("&&&" "&&"))))))
  (dolist (char-regexp ligatures)
    (set-char-table-range composition-function-table (car char-regexp)
                          `([,(cdr char-regexp) 0 font-shape-gstring]))))

```
4. "www" "&&" and "&&&" should be ligatured

**Comment by masm11** [comment]
thank you. confirmed.

**Comment by masm11** [comment]
I forgot to register harfbuzz font driver.
I registered it, and now ligatures work.

Try latest feature/pgtk on savannah.

![lig](https://user-images.githubusercontent.com/7226237/100463662-8aed2580-310f-11eb-8369-1e46c1601ebb.png)

**Comment by rainD4X** [comment]
Tested the newer commit, that fixed it. Thanks.
