### ISSUE TITLE
emacs-native-comp-git-enhanced - hyper key definitions do not work

### ISSUE THREAD

**Issue by xircon** [masm11/emacs#83]
I define my spacebar as a hyper key through a combination of xcape and xmodmap.  They work in the non-enhanced version in aur, but do not seem to register at all in the enhanced version.

Running KDE on X on Arch and the three hyper keys defined in sxhkd still work e.g. hyper-d for rofi is fine. I use sxhkd as plasma does not support hyper as a modifier.

I was trying to get emacs-webkit to work and the author suggested I post here.

**Comment by masm11** [comment]
Fixed on savannah latest feature/pgtk.  Could you try it?

I hope it works.

**Comment by xircon** [comment]
If I rebuild the aur package will that do it?

**Comment by akirakyle** [comment]
@xircon emacs-native-comp-git-enhanced is using the branch merging native-comp and pgtk here https://github.com/flatwhatson/emacs/tree/pgtk-nativecomp which has yet to update. Wait till the commit "db169f8134 Add support for hyper modifier key" shows up, then rebuild your aur package.

**Comment by xircon** [comment]
Thank you.

**Comment by masm11** [comment]
@xircon Is your hyper key working?

**Comment by xircon** [comment]
Yes, working fine.

**Comment by masm11** [comment]
thanks.
