### ISSUE TITLE
Scrolling using touch pad only partially works

### ISSUE THREAD

**Issue by ryanprior** [masm11/emacs#85]
### Summary

Scrolling a buffer using the touch pad doesn't work for the most part. Sometimes Emacs will scroll, but in large jumps that are not predictable or useful.

### Software and hardware versions
* `M-x` `emacs-version` says:
  >GNU Emacs 28.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0)

* `guix show emacs-next-pgtk` says:
  >version: 28.0.50-0.3df4ca4

* Operating system is elementary OS 5.1.7 Hera

* Hardware is a 2019 Dell XPS 13 with no peripherals attached

### How to trigger the issue

Start Emacs using: `guix environment --pure --ad-hoc emacs-next-pgtk -- emacs -Q`

Load a buffer and scroll using a touch pad. 

#### Expected behavior

Emacs should begin scrolling the buffer right away.

#### Observed behavior
Emacs mostly does not respond to touchpad scrolling at all. On occasion the buffer scroll position jumps suddenly in the direction I'm trying to scroll.

### Workarounds

* Keyboard scrolling works: I can scroll the buffer just fine using the `C-v`, `M-v`, etc
* GTK scrollbar works
* Touch-pad scrolling works in upstream Emacs 27 and 28

I don't observe any unusual or undesirable behaviors when scrolling using those methods. Only scrolling using the touch pad in the pgtk build seems to be affected.

### P.S.

THANK YOU for working on this fantastic software!

**Comment by masm11** [comment]
Thank you for the report with detail.

I fixed it.
Please try the latest feature/pgtk on savannah.

**Comment by ryanprior** [comment]
Your patch fixes the issue for me. I've submitted a patch to update the Guix package as well: https://issues.guix.gnu.org/44934

Thank you again!
