### ISSUE TITLE
Remove headerbar in Wayland session?

### ISSUE THREAD

**Issue by worldofgeese** [masm11/emacs#86]
In Wayland sessions, Emacs gains a very large headerbar at the top. Is there a method to tell Emacs pgtk on Wayland to disable the headerbar?

![image](https://user-images.githubusercontent.com/59834693/101291814-d2f50200-380b-11eb-97bd-70784ab0eb88.png)

**Comment by Thaodan** [comment]
Do you mean the window decoration?
That is the job of the window-manager.

**Comment by fejfighter** [comment]
@worldofgeese 

If you run emacs full screen with `<f11>` the headerbar will disappear

I'm not sure if there is a method  to keep the gnome bar above active, in full screen mode

**Comment by A6GibKm** [comment]
Yes it can be done in gtk (kinda), with a little work and has nothing to do with wayland.

If the window can be changed from GtkApplicationWindow to HdyApplicationWindow (using libhandy), the headerbar becomes not necessary and can be hidden at will (The headerbar should use HdyHeaderbar for this).

It might be possible also with css without the need for libhandy. Or simple calling headerbar.hide(), but I am not sure about that one.

**Comment by worldofgeese** [comment]
> Do you mean the window decoration?
> That is the job of the window-manager.
> 
> 
> 

That's right: some apps can have this headerbar disabled (such as Gnome Terminal) through a `gsettings` invocation. I'd like to know if there is any command like this available for this Emacs build as it's quite a visual nuisance.

**Comment by Thaodan** [comment]
Or fix your window manager instead of breaking other non-gnome users?

**Comment by worldofgeese** [comment]
> Or fix your window manager instead of breaking other non-gnome users?
> 
> 
> 

I invite you to speak kindly here: no need for micro-aggressions. No one is asking to break the experience for non-gnome users. There are many apps, such as Firefox, that appear to solve this out of the box (Firefox doesn't display a headerbar by default, for example). That's what this issue is about, can we signal to a Wayland Gnome session not to display the headerbar by default?

**Comment by masm11** [comment]
@worldofgeese Do you want this?
```elisp
(modify-frame-parameters nil '((undecorated . nil)))
```

**Comment by worldofgeese** [comment]
> ```emacs-lisp
> ```emacs-lisp
> (modify-frame-parameters nil '((undecorated . nil)))
> ```

Unfortunately, that doesn't signal to Gnome's Wayland session to not paint the headerbar.

**Comment by Emantor** [comment]
> > ```emacs-lisp
> > ```emacs-lisp
> > (modify-frame-parameters nil '((undecorated . nil)))
> > ```
> 
> Unfortunately, that doesn't signal to Gnome's Wayland session to not paint the headerbar.

As far as I know, gnomes wayland session enforces client side decorations, which are handled through gtk. I however don't know how to disable them for gtk-apps.

**Comment by masm11** [comment]
@worldofgeese 
I'm sorry.  The value should not be `nil`, but `t`.  Could you try this?

```elisp
(modify-frame-parameters nil '((undecorated . t)))
```

**Comment by worldofgeese** [comment]
@masm11 That worked! Thank you 🙇
