### ISSUE TITLE
PGTK makes emacs subject to GTK/GDK scaling breaking some ui elements

### ISSUE THREAD

**Issue by Thaodan** [masm11/emacs#89]
When using Emacs with feature/pgtk, it is subject to the DPI scaling of GTK/GDK. This can break come UI elements.

I noticed the following ui elements broke:
+  icons that should not scale at all or not to this size
+  mode-line (gets to big, simple-mode-line active with powerline theme)

![Screenshot_20201222_054349](https://user-images.githubusercontent.com/1747359/102846453-aef30c80-4418-11eb-83df-4053db8d9f17.png)

**Comment by masm11** [comment]
![a](https://user-images.githubusercontent.com/7226237/102892477-456c1000-44a3-11eb-979e-84cd22bd706a.png)

No problem.  Could you tell me how to reproduce?

**Comment by Thaodan** [comment]
Use emacs in --daemon mode with this unit:

```
[Unit]
Description=Emacs: the extensible, self-documenting text editor
Wants=graphical.target
Wants=environment.target

[Service]
Type=forking
ExecStart=/usr/bin/emacs --daemon
ExecStop=/usr/bin/emacsclient --eval "(kill-emacs)"
Environment=SSH_AUTH_SOCK=%t/keyring/ssh
Environment=GDK_SCALE=2
#Environment=GDK_DPI_SCALE=0.5
Restart=always
TimeoutStartSec=0
[Install]
WantedBy=default.target

# /home/bidar/.config/systemd/user/emacs.service.d/override.conf
[Service]
TimeoutStopSec=600

```

Then use modeline icons mode together with simple-modeline and powerline as 
theme.

**Comment by masm11** [comment]
> modeline icons mode 

What is this?  Is it contained in powerline or simple-modeline?

**Comment by Thaodan** [comment]
https://github.com/ryuslash/mode-icons

**Comment by masm11** [comment]
Thanks, but your issue does not reproduce.

![a2](https://user-images.githubusercontent.com/7226237/102904096-96383480-44b4-11eb-9906-162da0c73a20.png)

What DE/WM are you using?

**Comment by Thaodan** [comment]
Do you use high dpi scaling?

For normal 1.0 scaling everything is fine.

**Comment by masm11** [comment]
I use this config in wayfire:
```dosini
scale = 1.50000
```
and this config in given emacs.service:
```dosini
Environment=GDK_SCALE=2
```
and normal.

**Comment by Thaodan** [comment]
The error was on my side, I was using an old version of mode-icons-mode that 
was buggy this fix was missing: 

https://github.com/ryuslash/mode-icons/commit/
e29ab2899226c0c2afe00d774de541d1534d0cf7

Closing
