### ISSUE TITLE
Scrollbars do not have hover/pressed colors

### ISSUE THREAD

**Issue by oabdullah1** [masm11/emacs#96]
Scrollbars are always the same color, they don't change on hover or button press like they do in the regular emacs.

**Comment by masm11** [comment]
Thanks.  I did not notice.

I'm debugging.

**Comment by masm11** [comment]
Fixed in feature/pgtk on savannah.  Please try it.

**Comment by oabdullah0101** [comment]
I was locked out of my old GitHub account, so had to create a new one. Yes, the latest code in feature/pgtk fixes this issue. Thanks!
