### ISSUE TITLE
Clipboard not working with other apps when launched with systemd after reboot

### ISSUE THREAD

**Issue by declantsien** [masm11/emacs#98]
I have `systemctl enable --user emacs`.
  This happens only when I reboot my system,
  - Open a new client with `emacsclient -c -n`.
  - Yank some text from Emacs(GdkWaylandDisplay) and try to paste in Firefox(wayland), nothing happend. (vice versa)

  If I do `systemctl restart --user emacs` or open a new Emacs instance, then it(copy/paste) works fine.

  Compiled with `--with-pgtk --with-cairo --with-modules --with-native-compilation`,
  and the last commit is  https://github.com/emacs-mirror/emacs/commit/5b97b98daa7f61311c3662beecbeca7037505992

**Comment by masm11** [comment]
Try these on non-working emacs and working emacs.

```elisp
(getenv "DISPLAY")
(getenv "WAYLAND_DISPLAY")
```

They may be different between on non-working emacs and working emacs.

**Comment by declantsien** [comment]
//non-working Emacs
```
(getenv** "DISPLAY")"wayland-1"
(getenv "WAYLAND_DISPLAY")nil
```

//working Emacs
```
(getenv "DISPLAY")":0"
(getenv "WAYLAND_DISPLAY")"wayland-1"
```

It is different. Why is that?

**Comment by masm11** [comment]
When I tested in my environment, always this pattern:

```
(getenv "DISPLAY")"wayland-1"
(getenv "WAYLAND_DISPLAY")nil
```

and couldn't copy/paste from emacs to firefox.

I think this copy/paste issue is related to environment variables.
It needs more investigation.

**Comment by masm11** [comment]
I tried to fixed it.
Please try latest feature/pgtk.

**Comment by declantsien** [comment]
Nice, it works. I think it's OK to close this issue.

**Comment by masm11** [comment]
thanks for confirmation.
